### ISSUE TITLE
Check if tier system or donation system would work for extra tokens

### ISSUE THREAD

**Issue by SaskiaFuzzy** [kiezburn/dreams#10]
Waldo suggeste that we enable people to buy more tokens by donating. 
There were questions regarding the compability of this with the burner ticket email integration.
Questions: 

Would a free donation work? 
Would a 'tier system' (where people pay three different set levels of ticket fees) work?

**Comment by waldov86** [comment]
Here is the background: https://talk.kiezburn.org/d/4hsVyUIw/-advice-process-buy-dream-tokens-when-buying-ticket

**Comment by flov** [comment]
I didn't have the time to put some research into that.
I haven't talked with @hesslau about that yet. Maybe he can give more insight

**Comment by hesslau** [comment]
Since this idea is still in "propsal" mode and technically not an issue yet, the discussion around this should be kept on talk. If we go ahead with this proposal, we could reopen this issue.

Thread on Talk: https://talk.kiezburn.org/d/4hsVyUIw/-advice-process-buy-dream-tokens-when-buying-ticket
