### ISSUE TITLE
Counter on # Random Dreams not working 

### ISSUE THREAD

**Issue by waldov86** [kiezburn/dreams#11]
![2020-03-06 16_03_13-Kiez Burn Dreams](https://user-images.githubusercontent.com/38975752/76095213-2e1b6f00-5fc4-11ea-8209-f51bdbbaa137.png)
This counter currently mentions 48 dreams, but there are none. To me, this seems to mean that the counter does not work correctly at the moment.

**Comment by flov** [comment]
This isn't really a counter, it's static input that only works if there are 49 dreams ;)

**Comment by flov** [comment]
I've fixed this issue by removing this button and renaming it
