### ISSUE TITLE
Adjust "all dreams & stats"

### ISSUE THREAD

**Issue by waldov86** [kiezburn/dreams#12]
The page https://dreams.kiezburn.org/guideview needs some adjusting to our particular situation. Below the table as it should look like. The numbers are simply copied over, and should stay dynamic.

CURRENT | TOTAL | (%) OF TOTAL
-- | -- | --
Kiezburner participation (at least 1 heart given) | 0 | 3210 | 0.0%
Total grants given | 0 | 35481 | 0.0%
Total of minimum budgets (+ as % of total Dream budget) |   | 0 | NaN%

As a current placeholder for the total Dream budget, you can enter 20000

**Comment by flov** [comment]
noiced and changed
