### ISSUE TITLE
Change timer text in profile

### ISSUE THREAD

**Issue by waldov86** [kiezburn/dreams#13]
![image](https://user-images.githubusercontent.com/38975752/76096621-adaa3d80-5fc6-11ea-8a8c-abaa1149e509.png)

This requires 2 (temporary changes):
- change the timer to be ending 30th of April (we can change this later)
- text should read: "Don't miss out! Only xxx left to gift your dream tokens" (with the xxx being the counter)

**Comment by flov** [comment]
I saw that and in the app it's called `lockdown` functionality. Which gives a warning for upcoming deadlines.
There are three deadlines set in dreams:
  submit_dream: 2020-05-02t05:05:00+02:00
  safety_file: 2020-03-15t00:00:00+02:00
  granting: 2020-05-05t00:00:00+02:00

I think @waldov86 you are referring to the granting deadline.
Do you know what safety_file is about? I think it was a functionality that was added by borderland. I would disable it for now

**Comment by waldov86** [comment]
Interesting. I guess Dreams will need to be set up with the different deadlines for submission and granting deadlines. There is no need for a safety file deadline.

For now, the deadlines could be:
- submit_dream: 15th of May
- granting: 15 of April

- 

-

**Comment by flov** [comment]
Granting until the 15th of April and submitting a d ream one month attaer on the 15th of may? that doesn't make much sense :)

**Comment by flov** [comment]
Please provide the correct deadlines

**Comment by SaskiaFuzzy** [comment]
Submit Dream: 15th of April
Granting: 15th of May
