### ISSUE TITLE
Remove all mentions of safety sketches

### ISSUE THREAD

**Issue by waldov86** [kiezburn/dreams#14]
It is unlikely we will govern art installation safety through the Dreams platform. To avoid confusion, I would suggest to remove all mentions of the safety sketches.

In practice this means:
- remove the page https://dreams.kiezburn.org/dreams/85/safety_sketches
- remove the button to the safety page in the dream page (see screenshot)
![image](https://user-images.githubusercontent.com/38975752/76100194-8e161380-5fcc-11ea-83cb-45e24509723a.png)

**Comment by flov** [comment]
done
