### ISSUE TITLE
Add extra budget collum

### ISSUE THREAD

**Issue by waldov86** [kiezburn/dreams#15]
Current:
![image](https://user-images.githubusercontent.com/38975752/76103361-dc79e100-5fd1-11ea-8c22-570417d4f7e9.png)

In the Dream pages (example: https://dreams.kiezburn.org/dreams/85), the budget table:

- add in an extra row at the bottom that sums up the different amounts
- add a row below this that specifies how the minimum budget relates to it
- add another row below this that specifies how the target budget relates to it
- add an extra columns with the percentages of the budget items towards the total amount of the dream specified budget

Below how it ideally looks like:

**DESCRIPTION | AMOUNT (EUR) | % (of spedified budget)**
-- | -- | --
Puppy feed | 40 | 21%
wood for puppy mill | 100 | 53%
puppy water bowls | 50 | 26%
**Specified   budget** | **190** | **100%**
 |  | 
Minimum funding | 100 | 53%
Target funding | 250 | 132%

**Comment by flov** [comment]
the specified budget refers to the max funding? Maybe we need two more columns here one for min funding and one for max funding?

**Comment by flov** [comment]
<img width="750" alt="Screen Shot 2020-03-08 at 13 29 40" src="https://user-images.githubusercontent.com/96314/76162777-ed953000-6140-11ea-8305-5a117a803502.png">
Done

**Comment by flov** [comment]
jjjj
