### ISSUE TITLE
Dream submission: change questions&descriptions

### ISSUE THREAD

**Issue by waldov86** [kiezburn/dreams#16]
I indicated in yellow or orange what we should change in terms of questions, and the descriptions under the questions: 
https://docs.google.com/document/d/1niLaLU4LFQZbE-ob8eDjM-hhHxOZDFeDRLe639ZAieQ/edit#

**Comment by SaskiaFuzzy** [comment]
+ Added the category question

**Comment by flov** [comment]
I can't see the category question
