### ISSUE TITLE
UPDATE Dream page texts to 2020 versions

### ISSUE THREAD

**Issue by SaskiaFuzzy** [kiezburn/dreams#17]
### Start Page

URL: https://dreams.kiezburn.org
 
**Old text for reference:** 

Congratulations! You've stumbled upon something special! Kiez Burn is some awesome fucking shit. We dream together and breathe life into our mad and wondrous creations. Dreams need matter to come to life, and this is where we share resources to make that happen. 

In order to register on this platform, you need to purchase a ticket for Kiez Burn 2019 on Burnertickets. Ticket sale will start on Friday, April 5th at 1pm. 

Update on Dreams Timeline!
Dream submissions will close on 30 April! You can vote for Dreams until 5 May. After 5 May your tokens will be reallocated. We hope to have a final decision on Dreams by 7 May

There is a video tutorial on How to use Dreams. You can find more information about Kiez Burn in our Forum and our website.
 

**Replace with:** 

Hello dear friend and welcome to the Dreams Platform. Here we share our dreams and together we breathe life into our mad and wondrous creations. You are Kiez Burn, so you decide what will be realised! Same as last year your ticket is linked to dream tokens, which you can spend on the projects you want to make happen. Let’s vote and fill our playa with amazing art!
 
In order to register on this platform, you need to purchase a ticket for Kiez Burn 2020 The ticketing team is working hard to start the ticket sale soon. Stay updated by signing up for the Kiez Burn Newsletter! [Klick here!](https://kiezburn.us15.list-manage.com/subscribe?u=71f32d7881553bdbe047a1724&id=57194cd3d5) 
 
Here is a video tutorial on How to use Dreams. [Klick here!](https://www.youtube.com/watch?v=S0cI1fhLoRc&feature=emb_title )
You can find more information about Kiez Burn in our Forum [(Klick)](https://talk.kiezburn.org/dashboard ) and our website [(Klick)](https://kiezburn.org ).
Also, if you wish to get in touch with dream guides and other dreamers, please visit the Dreamer 2020 group on talk [(Klick here)](https://talk.kiezburn.org/dreams-dreamguiding-2020/).
 
Preliminary Dreams Timeline: 
 
Sun 8th March: Launch Dreams Platform ⇒ Dreamers can upload their dreams!
End of March: Ticket Sale and voting starts – End of Dream Submission? 
End of April: End of Voting, Token reallocation 
Beginning of May: Final Decision / Funding announcement

### FAQ PAGE

 Url: https://dreams.kiezburn.org/pages/faq-en#2

**Change text to**
Because Dreams are fun! Taking decentralisation and self-organisation seriously, we decided to distribute art grants this year via the Dreams platform. It works pretty much like Kickstarter, Startnext, Betterplace, GoFundMe etc.

The Dreams platform is a powerful way of engaging the wider community to interact directly with the artists and art on the event. You will decide how your ticket revenue is being used.

URL
https://dreams.kiezburn.org/pages/faq-en#3

*Keep**
What are the Dream Guides?
Dream Guides are volunteers who co-create the event by guiding dreamers to make their projects happen and facilitate the art grant process at Kiez Burn on the Dreams platform. If you want to help other Burners to make their dreams come true – please join the team! We still need support here.

**Remove** 
Everything starting at 
HOW TO GET STARTED

URL:
https://dreams.kiezburn.org/pages/faq-en#4
 
**Replace with**

Before you submit a Dream, please read the Dreamer Manual [(Klick here!)](https://talk.kiezburn.org/d/HQmGxOcb/-placeholder-manual-for-dreamers-read-this-if-you-want-to-submit-a-dream) carefully. There you can find information about the types of projects eligible for refunds in 2020.
You must self assign your Dream to one of several categories. If you cannot assign yourself, a Dream guide will help you to sign up. 

Only Art, Performances and Workshops will be funded this year. No infrastructure, no Camps or gifting. If an art project is run by a Camp it has to be placed on the art plateau or areas designated for art - not within a camp’s area. Hosting workshops, or giving a performance at a Camp, is no problem though. Intoxicants (including alcohol), vehicle costs and fines for illegal acts cannot be refunded. In an attempt and experiment to promote more ART on Kiez Burn 2020, categorizing as an ART project this year comes with advantages.
Again: Please read the Dreamer Manual to check if your dream is eligible for funding! 

https://dreams.kiezburn.org/pages/faq-en#6 

**REMOVE:** 

I have an infrastructure grant, but I need my minimum funded, what is up.
The minimum amount for critical infrastructure – example: Electricity – will be funded outside of the Dreams platform. Other infrastructure dreams will be assured a minimum on the dreams platform, like toilets. We are sure you all want to shit in style, so let's all vote for fantastic toilets!
Your Minimum is the amount of money you NEED in order to bring the project. Once your project collected enough votes to pass the minimum threshold, you will be notified, and your project is sure to receive funding.
Your Maximum is how much you need to realize the perfect version of your project. Any money you receive after having passed the minimum can be used for your project.
 

URL:
https://dreams.kiezburn.org/pages/faq-en#7
Although every vote does count for a certain monetary value, we cannot determine at this point yet how much every vote will be worth. The value of tokens might change up until voting is enabled.

**Comment by flov** [comment]
awesome! Will implement it now
