### ISSUE TITLE
Bug report for Dreams 

### ISSUE THREAD

**Issue by SaskiaFuzzy** [kiezburn/dreams#19]
Flo, please let me know what could work.

A new page which is 'Report bugs' which either leads to a contact sheet (with an email that it sends the bug reports to) or poses an email or links to talk or links to this github.

I would prefer some bug report system that doesn't require sign up. I will see that I re-activate the dreams kiezburn mail address so we can use this one maybe? 

It could help us in the early phase of dream to find the stuff we might be missing.

**Comment by flov** [comment]
Ideally people should file bugs on this github issues page.
If people don't want to signup then you can also send me an email: florian.vallen@gmail.com :)

**Comment by SaskiaFuzzy** [comment]
Then add this :) 
(Either in a new page saying 'Found a bug?' or 'Bug?' or something on top or in a text box where it is convenient)

"If you find a thing not working on dreams, feel free to file an [issue on github](https://github.com/kiezburn/dreams/issues) or write an email to our rech wizard: florian.vallen@gmail.com . Thanks <3."
