### ISSUE TITLE
Put certain dream team members in a position to enable or disable view & voting of dreams 

### ISSUE THREAD

**Issue by SaskiaFuzzy** [kiezburn/dreams#21]
So last year I had the ability to hide dream projects or to make them visibile, as well as to enable voting on the dream with dream tokens once the requirements were checked and there was a green light. 

We need to implement that function again, unless you wish to enable every dream by hand, Florian ;). Ideally I find more poeple who wish to take on that task with me. :) These also need have their accounts enabled for that

**Comment by flov** [comment]
This feature is there.
If you are an admin you can see all the dreams that don't have granting enabled. They have a lock in the upper right corner of the image in the overview.
If you go to the dream you have several options to approve them ( see screenshots attached )

<img width="384" alt="Screen Shot 2020-03-11 at 18 33 38" src="https://user-images.githubusercontent.com/96314/76446385-4970ea80-63c7-11ea-9b1c-c706a2c4ad70.png">
<img width="1272" alt="Screen Shot 2020-03-11 at 18 34 33" src="https://user-images.githubusercontent.com/96314/76446390-4b3aae00-63c7-11ea-8c85-74836fe77bc4.png">

**Comment by hesslau** [comment]
User accounts can receive admin right by running this in the rails console:
>  User.find_by(email:"test@example.com").update(admin:true)

PS: @SaskiaFuzzy your account has admin rights now. Let @flov or me know if there is another account that needs to be admin.
