### ISSUE TITLE
Change text on start page, incorrect information 

### ISSUE THREAD

**Issue by SaskiaFuzzy** [kiezburn/dreams#22]
URL: https://dreams.kiezburn.org/

Issue mentioned by Waldo in this talk comment: https://talk.kiezburn.org/d/1b7JY3Wr/dreams-2020-stage-1-launch-dreamers-submit-dreams/16?fbclid=IwAR2_Z7pXTcc5Z2fnggAAdo1uEQPmP8rgih2Egnpcv1_W8MHQn3ajx0ciBso

> This statement is incorrect. I believe this is also a blocker for release. Dreamers can register on the platform and submit their Dream. They just should register with the same email as used on Burner Tickets.
> 
> Suggested text: "Please register on this platform by using the same email as you will use to purchase a ticket. The ticketing team is working hard to start the ticket sale soon. Stay updated by signing up for the Kiez Burn Newsletter! Click here!"

**Now I do **understand...**** That this is actually currently the case. Only people who have a ticket can register. If that is the case, that needs to be changed. Everybody should be able to register / upload a dream, regardless of them having a 2019 ticket.

**Comment by flov** [comment]
Yep, this has been fixed

**Comment by SaskiaFuzzy** [comment]
Issue has not been fixed. Old text is still on platform.
