### ISSUE TITLE
Change categories & Category text !!!!

### ISSUE THREAD

**Issue by SaskiaFuzzy** [kiezburn/dreams#23]
URL: https://dreams.kiezburn.org/dreams/new

Change Category and text under Category to the Following

---START OF TEXT--- 

Please self- assign your dream to one of the following categories.
For a throughout description of the categories, please refer to the [manual for dreamers.](https://talk.kiezburn.org/d/HQmGxOcb/manual-for-dreamers-read-this-if-you-want-to-submit-a-dream). 

---END OF TEXT---
---CATEGORIES---

- Art and Installation 
- Performance
- Interactive Projects to Explore
- Workshop 
- Communal Place 
- None of the above (please have a dream guide contact me) 

--- END ---

**Comment by flov** [comment]
done 🎉
