### ISSUE TITLE
Some aesthetic edits

### ISSUE THREAD

**Issue by SaskiaFuzzy** [kiezburn/dreams#24]
Hei Flo,

thanks for updating the categories. It looks a bit messed up tho (see picture below)

Can you make it so  Categories is a written  with a capital 'C' in the beginning and that the description text is under the category instead of above? Thx. 

<img width="655" alt="Bildschirmfoto 2020-03-11 um 18 36 53" src="https://user-images.githubusercontent.com/61835262/76446575-90f77680-63c7-11ea-804d-666c653fca33.png">

**Comment by flov** [comment]
ok, C of category is big now and the first form element
