### ISSUE TITLE
Some more text edits

### ISSUE THREAD

**Issue by SaskiaFuzzy** [kiezburn/dreams#25]
URL: https://dreams.kiezburn.org/

**Add text that is written in BOLD (do not add it in bold tho)**
(...) Also, if you wish to get in touch with dream guides and other dreamers, please visit the Dreamer 2020 group on talk.
 **You can also contact us via email: dreams@kiezburn.org** 

****

Preliminary Dreams Timeline:
(...)

**Comment by flov** [comment]
done
