### ISSUE TITLE
Category? 

### ISSUE THREAD

**Issue by SaskiaFuzzy** [kiezburn/dreams#27]
Hei Flo,

it is great that we have the category now. 

BUT I can not see the category the people chose. Neither can  I see it when I click 'edit' on the dream, nor does it correspond to any textbox in the dream description.

Can the category be displayed? 

What it should say:
**Category**
//Whatever the person chose in the dropdown menu// 

Ideal placement: 
On the top of the main text (over 'Summary')

OR

To the right in the 'DETAIL' box on the very top (over the Website)

**Comment by flov** [comment]
I've done all of the above, you can see the category in the edit form now (but cannot edit it) and it's visible on the dreams show page in both places as you described
