### ISSUE TITLE
Create category system in dream signup system + sort ART first 

### ISSUE THREAD

**Issue by SaskiaFuzzy** [kiezburn/dreams#7]
Goal page: https://dreams.kiezburn.org/dreams/new

**Tasks**

- [x] Create category for dreamers to self-assign to when uploading their dream.
- [ ] Change algorithm so dreams in of the category ART are shown at top of the list 

**Idea**
Create a dropdown menu. 

**Text over menu**
Please assign yourself to a category. 
You can read more about the categories, why they exist and what they mean in the manual [ENTER FUTURE LINK HERE]. 

**Dropdown menu**

- ART 
- Performance / Workshop 
- Workshop space / Workshop place 
- None of the above (please have a dream guide contact me)

**Comment by waldov86** [comment]
@SaskiaFuzzy I would recommend to change "ART" to "art installation"

The link can already be entered: https://talk.kiezburn.org/d/HQmGxOcb/-placeholder-manual-for-dreamers-read-this-if-you-want-to-submit-a-dream

**Comment by flov** [comment]
I've completed the category task. The sorting on the homepage shoudn't be a big deal but will still have to be implemented. It will have to wait for another day.
